"""empty message

Revision ID: 9296728a80df
Revises: 
Create Date: 2024-09-27 14:49:47.618213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9296728a80df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('dadosDict', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('operador_maquina',
    sa.Column('operador_id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['operador.id'], ),
    sa.PrimaryKeyConstraint('operador_id', 'maquina_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operador_maquina')
    op.drop_table('operador')
    op.drop_table('maquina')
    # ### end Alembic commands ###
