"""empty message

Revision ID: 4d1885c4b57b
Revises: 9296728a80df
Create Date: 2024-10-10 19:09:56.843790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1885c4b57b'
down_revision = '9296728a80df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipoMensagem', sa.Text(), nullable=False),
    sa.Column('idMaquina', sa.Integer(), nullable=False),
    sa.Column('idOperador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idMaquina'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['idOperador'], ['operador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao')
    # ### end Alembic commands ###
