"""empty message

Revision ID: 605ccc1d4da5
Revises: b2c53d771f99
Create Date: 2024-10-14 21:38:06.252891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '605ccc1d4da5'
down_revision = 'b2c53d771f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipoMensagemMax', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tipoMensagemMin', sa.JSON(), nullable=True))
        batch_op.drop_column('mensagemMax')
        batch_op.drop_column('mensagemMin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensagemMin', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('mensagemMax', sqlite.JSON(), nullable=True))
        batch_op.drop_column('tipoMensagemMin')
        batch_op.drop_column('tipoMensagemMax')

    # ### end Alembic commands ###
