"""empty message

Revision ID: 7a25006c0bf7
Revises: cf0d1e51981d
Create Date: 2024-10-14 20:13:34.063860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a25006c0bf7'
down_revision = 'cf0d1e51981d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maxDict', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('minDict', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.drop_column('minDict')
        batch_op.drop_column('maxDict')

    # ### end Alembic commands ###
