"""empty message

Revision ID: cf0d1e51981d
Revises: db2830b6bd44
Create Date: 2024-10-14 20:01:25.928156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'cf0d1e51981d'
down_revision = 'db2830b6bd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.drop_column('max')
        batch_op.drop_column('min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('max', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
