"""empty message

Revision ID: db2830b6bd44
Revises: 4d1885c4b57b
Create Date: 2024-10-10 19:52:54.415039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2830b6bd44'
down_revision = '4d1885c4b57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('min', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.drop_column('min')
        batch_op.drop_column('max')

    # ### end Alembic commands ###
