"""empty message

Revision ID: e02f4548d913
Revises: 605ccc1d4da5
Create Date: 2024-10-14 21:49:44.734687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e02f4548d913'
down_revision = '605ccc1d4da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipoMsgMax', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tipoMsgmMin', sa.JSON(), nullable=True))
        batch_op.drop_column('tipoMensagemMin')
        batch_op.drop_column('tipoMensagemMax')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipoMensagemMax', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tipoMensagemMin', sqlite.JSON(), nullable=True))
        batch_op.drop_column('tipoMsgmMin')
        batch_op.drop_column('tipoMsgMax')

    # ### end Alembic commands ###
