"""empty message

Revision ID: fb9200dcf7a9
Revises: e02f4548d913
Create Date: 2024-10-14 21:54:04.958143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fb9200dcf7a9'
down_revision = 'e02f4548d913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipoMensagemMax', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tipoMensagemMin', sa.JSON(), nullable=True))
        batch_op.drop_column('tipoMsgmMin')
        batch_op.drop_column('tipoMsgMax')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipoMsgMax', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tipoMsgmMin', sqlite.JSON(), nullable=True))
        batch_op.drop_column('tipoMensagemMin')
        batch_op.drop_column('tipoMensagemMax')

    # ### end Alembic commands ###
